import '../../../node_modules/jquery/dist/jquery.min'
import '../../components/dropdown/dropdown'
import '../../components/date-mask/date-mask'
import '../../js/jquery.mask.min.js'
import '../../../node_modules/air-datepicker/dist/js/datepicker.min'
import '../../components/datepicker/datepicker'
// import '../../components/calculator/calculator'
import '../../components/checkbox-list/checkbox-list'
import '../../components/like-button/like-button'
import '../../components/rate-button/rate-button'
import '../../../node_modules/ion-rangeslider/js/ion.rangeSlider.min'
import '../../components/range-slider/range-slider'
import '../../../node_modules/paginationjs/Gruntfile'
import '../../../node_modules/tui-pagination'
import '../../../node_modules/flaviusmatis-simplePagination.js-e32c66e/jquery.simplePagination'
import '../../components/pagination/pagination'
import '../../../node_modules/slick-carousel/slick/slick.min'
import '../../cards/room-slider/room-slider'
//SCSS imports
import './search-room.scss'

